version: '2'

services:
  iredMail:
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ZyVYmLGLkQgcDEkU7ZYb4xNHZYmmPrMC
      MARIADB_DATABASE: vmail
      MARIADB_USER: vmail
      MARIADB_PASSWORD: sx4fDttWdWNbiBPsGxhbbxic2MmmGsmJ
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    ports:
      - 8806:3306
    

